export const LOAD_DATA = "LOAD_DATA";
export const CHANGE_MEASURES = 'CHANGE_MEASURES';
export const CHANGE_MEASURES_WEIGHT = 'CHANGE_MEASURES_WEIGHT';
export const CHANGE_GOAL_WEIGHTS = 'CHANGE_GOAL_WEIGHTS';
export const CALCULATE_VALUE = 'CALCULATE_VALUE';